# Generated by Django 3.1.2 on 2020-10-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapist',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre de usuario'),
        ),
    ]
