# Generated by Django 3.1.2 on 2020-10-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option',
            field=models.ManyToManyField(blank=True, to='psychoApp.Option', verbose_name='Opciones'),
        ),
    ]
