# Generated by Django 3.1.2 on 2020-10-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychoApp', '0002_auto_20201012_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option',
            new_name='options',
        ),
    ]
