# Generated by Django 3.1.2 on 2020-10-08 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psychoApp', '0002_terapist_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapist',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='terapist',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
