name: code_check

on: [pull_request]

jobs:
  backend_linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back/
    steps:
      - uses: actions/checkout@v1
      - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fail if "new" violations detected or "any", default "new"
          failIf: new
          args: "--ignore=E203,E266,E501,W503,F403,F401 --max-line-length=88 --max-complexity=18 --select=B,C,E,F,W,T4,B9 --exclude=.git,__pycache__,venv"
      - uses: jpetrucciani/black-check@master
        with:
          path: "./"
