name: code_check

on: [pull_request]

jobs:
  backend_linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back/
    steps:
      - uses: actions/checkout@v1
      - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fail if "new" violations detected or "any", default "new"
          failIf: new
          args: "--config=.flake8"
      - uses: jpetrucciani/black-check@master
        with:
          path: "./"
